### ISSUE TITLE
Can't import React

### ISSUE THREAD

**Issue by risenforces** [0xF6/mana_lang#54]
**Describe the bug**
`import React from 'react'` doesn't work.

**To Reproduce**
Try to import React

** Code To Reproduce **
```csharp
import React from 'react'
```

**Expected behavior**
React being imported.

**Platform (please complete the following information):**
 - (required) OS: MacOS 11.4
 - (optional) VSCode Version: 1.57.1

**Additional context**
I want pizza

**Comment by 0xF6** [comment]
Try 
```mana
#use "facebook/react"
```

**Comment by risenforces** [comment]
@0xF6 I can't find `#` on my keyboard since I don't use `id` attribute on HTML elements, what's the solution?

**Comment by 0xF6** [comment]
> @0xF6 I can't find `#` on my keyboard since I don't use `id` attribute on HTML elements, what's the solution?

Try connect your keyboard to pc, you may have a problem with that, but i believe in you :trollface:
