### ISSUE TITLE
Migrate from xunit to nunit

### ISSUE THREAD

**Issue by 0xF6** [0xF6/mana_lang#69]
![image](https://user-images.githubusercontent.com/13326808/124355162-77abb680-dc18-11eb-8988-db1a2b5be35c.png)

Due to the problem of undefined behavior during the execution of tests and getting the error `There is no currently active test.`, it is necessary to migrate from xunit to nunit.

The research of problem did not reveal a solution:
xunit/xunit/issues/2146
xunit/xunit/issues/2003
xunit/xunit/issues/1540

- [x] ishtar test
- [x] compiler test
- [x] parser test

**Comment by orihomie** [comment]
uint's

**Comment by 0xF6** [comment]
Fixed~
Damn habit, thank you: D
